### ISSUE TITLE
Erro in HTML

### ISSUE THREAD

**Issue by joaoeudes7** [renatosistemasvc/soft-angular-mask#1]
Can't bind to 'mask' since it isn't a known property of 'input'.

**Comment by renatosistemasvc** [comment]
Please provide more details about when the error occurred. 

How did you use the library in your html? 

It seems to me that the problem is related to library installation. The angular has not identified the directive.

Could you let me know how you performed the entire process from installation to the use of the library?

**Comment by joaoeudes7** [comment]
I added the package in package.json;
I added the import in app.module.ts;
And then I used the Mask tag in html

**Comment by renatosistemasvc** [comment]
You must use the directive: `mask-number`.
exemple of input:

`<input mask-number [mask]="'99999-999'" name="valCode" [(ngModel)]="valCode">`

Take the test and post the result here

**Comment by joaoeudes7** [comment]
![captura de tela de 2017-08-24 19-02-22](https://user-images.githubusercontent.com/16367752/29690864-1827cdb8-88ff-11e7-8877-d2eccdf8266d.png)

**Comment by renatosistemasvc** [comment]
Vi aqui pelo seu código, parece que você é Brasileiro?

para seu código funcionar, você deve usar o seguinte:

`<input formControlName="sigla" pInputText [(ngModel)]="_entity.sigla" mask-number [mask]="'AA'" />`

é preciso usar a tag para indicar que se trata de uma diretiva: `mask-number`. Também é preciso rodar o comando npm install soft-angular-mask --save ou então, se você informou manualmente o pacote no arquivo json, você só precisar rodar o comando npm install.

agora analisando o seu input. Não entendi o que você quer fazer. Essa mascara que você criou apenas imprimirá as letras AA. Não fará mascaramento de nenhum número. Não compreendi o que vc quer fazer. Lembrando que para fazer o mascaramento de, por exemplo, um número de telefone, você vai usar o seguinte em seu input:

`mask-number [mask]="'(99) 999999999'"`

quando alguém digitar algo no input, a formatação ficará assim: (77) 988797678

**Comment by joaoeudes7** [comment]
Sou sim, estava em dúvida se você também era Brasileiro kkkk
Eu rodei o npm install após definir no package.json, e quanto ao 'AA' deixei assim porque vi padrões em alguns pacotes que assim iria aceitar apenas letras, tem alguma documentação referente mascarar apenas dois dígitos Maisculos por exemplo?
Obrigado pela ajuda, desde já

**Comment by renatosistemasvc** [comment]
Desculpa a demora. Tive problemas pessoais e estava sem acessar nos últimos dias. Então, este projeto mascara apenas números. não é possível mascarar letras. Abraço.

sobre a sua questão do erro, a biblioteca só funcionará se você acrescentar a diretiva desta forma no seu input:

`mask-number [mask]="'(99) 999999999'"`
