### ISSUE TITLE
Mask-number directive applies the masks in model attributes.

### ISSUE THREAD

**Issue by lslm** [renatosistemasvc/soft-angular-mask#2]
**Issue**
When I apply the "mask-number" directive in an input and check the model attributes it is possible to see the attributes with the masks.

**Steps to reproduce**
`<input mask-number [mask]="'(99) 9999 9999'" class="form-control"[(ngModel)]="newCliente.telefone.telefone_1" id="telefone-1">`
Rendered value: (11) 4798 5523
Model attribute value: `"(11) 4798 5523"`

**Question**
Is it possible to have the same behavior as the "mask-money" directive?
`<input mask-money [prefix]="'R$'" class="form-control" (change)="updatePrices()" [(ngModel)]="newContratoFornecimento.preco_bandeja" id="preco-bandeja">`
Rendered value: R$ 25,58
Model attribute value: `25.58`

**Comment by renatosistemasvc** [comment]
Do you want to have the value without the mask?

Rendered value: (11) 4798 5523
Model attribute value: "114798 5523"

this is what you want?

**Comment by lslm** [comment]
Exactly. I need the value in the model without the mask. When I use the 'mask-money', it works pretty well.

**Comment by renatosistemasvc** [comment]
I understood. Are you Brazilian?

Vi que você é brasileiro.
Vou implementar essa possibilidade amanhã até domingo e segunda já estará disponível, ok?

**Comment by lslm** [comment]
Sou brasileiro sim :)
Muito obrigado, Renato! Esse componente de máscara que você criou é o melhor que eu testei até agora. Valeu mesmo e espero poder contribuir de alguma forma!

**Comment by renatosistemasvc** [comment]
Obrigado, amigo. Estou finalizando a atualização já. Vai sair ainda esta semana. Estou trabalhando em outras bibliotecas e por isso o atraso. Mas ainda no meio desta semana sai. grande abraço!

**Comment by renatosistemasvc** [comment]
Solicitação implementada!

A partir de agora, a saída padrão em v-model é sem máscara.
Caso o usuário prefira a saída mascarada, será necessário usar a diretiva.

`[maskkOutput]="true"`

@SouUmLucas caso encontre alguma inconsistência ou bug, nos informe imediatamente para resolvermos. Caso tenha novas solicitações de melhorias, por favor, sinta-se encorajado a publicar aqui. A sua solicitação de melhoria foi postada na descrição da página inicial da biblioteca.

grande abraço, amigo!

---------------------------------------------------------------------------------------------------------------------

Solicitacion accepted and implemented.
The output of v-model is now unmasked (default behavior).
The developer will use the directive

`[maskkOutput]="true"
`
to activate the mask output

**Comment by lslm** [comment]
Muito obrigado, Renato. Já atualizei o projeto que estou trabalhando com a nova versão do componente e funcionou perfeitamente!
Mais uma vez, obrigado pela dedicação e um forte abraço!
