### ISSUE TITLE
Conflict with [disabled] directive

### ISSUE THREAD

**Issue by jcangelosi** [renatosistemasvc/soft-angular-mask#6]
When i try to use the directive [disabled] to disable the field that has a mask based on a boolean condition it doesnt work, it seems like a conflict with "ng-reflect-is-disabled" add to the input by the mask. Disabled alone works fine, the problem is with the directive.

**Comment by jcangelosi** [comment]
Fixed it by using [attr.disabled]="boolean ? true : null"

**Comment by MuhammedGenco94** [comment]
It is still not working for me !! 
I tried your solution but it is not reflected at all in page html.
